In [1]:
import requests
import pandas as pd
import csv

In [5]:
paperId = "10.1063/1.1671082"

# Define the API endpoint URL
url = f"http://api.semanticscholar.org/graph/v1/paper/{paperId}"

# Define the query parameters
query_params = {"fields": "title,authors,references,year"}

# Send the API request
response = requests.get(url, params=query_params)

# Check response status
if response.status_code == 200:
   response_data = response.json()
   # Process and print the response data as needed
   print(response_data)
else:
   print(f"Request failed with status code {response.status_code}: {response.text}")

{'paperId': '75e6daf6daea4141a1be410ef8e4de2b5a124e71', 'title': 'High‐Temperature Dependence of Electron and Hole Mobilities in Anthracene Crystal', 'year': 1969, 'authors': [{'authorId': '12146551', 'name': 'J. Fourny'}, {'authorId': '74241469', 'name': 'G. Delacote'}], 'references': [{'paperId': '96f964d99a329c7e9ec26d4a59b9d36b53240c31', 'title': 'Intrinsic Photoconduction in Anthracene Crystals'}, {'paperId': 'bded117f68c77a9945db2d2c7bdb0acdb4fae8c0', 'title': 'Linear-Response Theory of the Electron Mobility in Molecular Crystals'}]}

In [18]:
url = 'https://api.semanticscholar.org/graph/v1/paper/batch'
query_params = {"fields": "title,authors,citationCount,references,url,fieldsOfStudy,year,isOpenAccess,externalIds,paperId,publicationDate,embedding"}
r = requests.post(
    url,
    params= query_params,
    json={"ids": ["649def34f8be52c8b66281af98ae884c09aef38b", "ARXIV:2106.15928"]}
)
print(r.json())
print(type(r.json()))

[{'paperId': '649def34f8be52c8b66281af98ae884c09aef38b', 'externalIds': {'MAG': '2801930304', 'DBLP': 'conf/naacl/AmmarGBBCDDEFHK18', 'ACL': 'N18-3011', 'ArXiv': '1805.02262', 'DOI': '10.18653/v1/N18-3011', 'CorpusId': 19170988}, 'url': 'https://www.semanticscholar.org/paper/649def34f8be52c8b66281af98ae884c09aef38b', 'title': 'Construction of the Literature Graph in Semantic Scholar', 'year': 2018, 'citationCount': 379, 'isOpenAccess': True, 'fieldsOfStudy': ['Computer Science'], 'publicationDate': '2018-05-06', 'embedding': {'model': 'specter_v1', 'vector': [-8.82082748413086, -2.6610865592956543, 0.8936576843261719, 0.26382559537887573, 1.513496994972229, -1.0313653945922852, 0.7256110906600952, 2.080476999282837, 0.8230894804000854, 4.205087661743164, -0.9822302460670471, -0.03232526779174805, -2.4075639247894287, -0.9867752194404602, -1.921100378036499, 0.7259652018547058, -0.7707503437995911, -3.645012140274048, 3.874178647994995, 1.7716397047042847, 3.568206787109375, 0.44507932662963867, -4.567941188812256, -6.441675662994385, 2.8164267539978027, -5.735928535461426, 4.397401332855225, 1.8640488386154175, -2.0923988819122314, -2.627096176147461, -0.7487516403198242, -2.0460338592529297, 4.951084613800049, 0.1367805004119873, 0.11137333512306213, -4.1136651039123535, -2.594398021697998, 3.030726671218872, 0.3192863166332245, 0.5330687761306763, 2.1357359886169434, -5.069549560546875, 3.3368606567382812, 3.4393889904022217, -0.4198175370693207, -1.4004586935043335, -0.5914772748947144, 2.3206048011779785, 0.7648448348045349, -1.597121000289917, -0.385739803314209, -3.156200885772705, 2.498971462249756, 0.8303604125976562, 2.0128214359283447, -3.782414197921753, 2.528552770614624, 2.332465410232544, 2.5369043350219727, -5.0995683670043945, -1.626462459564209, 7.199328422546387, -1.2566406726837158, 0.41538551449775696, 3.7755417823791504, 1.261708378791809, -7.584755897521973, 4.0944390296936035, 1.5449888706207275, -4.304090976715088, -0.32924726605415344, -2.4089677333831787, 1.7628121376037598, -0.09815728664398193, -0.6447533965110779, 0.45084691047668457, 1.3999435901641846, -3.6956005096435547, -2.3098721504211426, 0.3901975452899933, 1.029798984527588, -2.0560712814331055, -0.5374155044555664, 4.123762607574463, 3.3944759368896484, -1.5951069593429565, 2.828338623046875, 0.5641002058982849, 0.22941206395626068, -0.47985130548477173, 1.9426360130310059, 2.0136306285858154, 1.179512619972229, 4.003891944885254, -0.33438336849212646, -1.1228828430175781, -1.2929275035858154, 1.5840518474578857, 1.3768726587295532, -0.4870491623878479, 2.6818037033081055, 2.0074918270111084, 2.363792896270752, -1.722172737121582, 5.0640130043029785, -3.042407274246216, 3.3051280975341797, 0.8497027158737183, -0.07694533467292786, 1.968888521194458, -1.099830150604248, -0.5580379366874695, 0.7135522961616516, -2.482787847518921, -1.3170889616012573, -5.876715660095215, -0.6423283815383911, -1.3246173858642578, -3.658334255218506, 1.5349525213241577, -0.7668131589889526, 0.7902154922485352, -3.750441551208496, 2.065319299697876, 0.018029093742370605, -3.6421332359313965, -0.37890782952308655, -2.2164065837860107, -0.08748644590377808, -3.86814022064209, 0.695722222328186, 4.275792121887207, 3.413512945175171, 0.7553334832191467, -1.4113353490829468, 0.6299422979354858, -2.747424364089966, 3.451552152633667, -3.1597602367401123, -0.7350130081176758, -1.1627154350280762, 5.0071563720703125, -0.8610213398933411, -0.9394667148590088, -5.773488998413086, 5.3121795654296875, 3.149068832397461, 1.1553789377212524, -0.6007860898971558, 3.3248229026794434, 2.350024461746216, -3.4872894287109375, -0.8592612743377686, 3.839386463165283, -1.9614695310592651, 2.8497214317321777, -2.9465718269348145, 3.018148899078369, -0.16511030495166779, -0.09398387372493744, 3.38796329498291, 0.2834477722644806, -3.7649965286254883, 0.698212206363678, 1.2958242893218994, 0.10116651654243469, -5.703367233276367, 4.123208045959473, -2.971092462539673, 4.6502861976623535, 0.606526255607605, -2.1402676105499268, 1.6209194660186768, -0.5743860006332397, -2.4197378158569336, -1.5533453226089478, -4.110861778259277, -3.6292262077331543, -1.4521592855453491, 0.3719058930873871, -0.9718815088272095, -0.3786925971508026, -5.524031639099121, 0.33255061507225037, -4.376255035400391, 2.3065083026885986, -0.19468218088150024, -2.940129041671753, -1.9395620822906494, -1.6664588451385498, -1.8545734882354736, -3.5772130489349365, 3.8606462478637695, 3.4952049255371094, 2.122180461883545, 5.525038719177246, 5.132749557495117, 0.6683793067932129, -1.7433147430419922, 2.5299510955810547, -0.0620303750038147, 3.5391602516174316, 0.09924519062042236, 2.936466932296753, 1.0871052742004395, 2.5235912799835205, 0.608716607093811, 6.6861748695373535, -0.050266146659851074, -0.5016537308692932, 0.4177108108997345, 1.5648516416549683, 0.6080945730209351, 4.140994071960449, 0.10780242085456848, -2.273747682571411, -3.999650478363037, -1.93492591381073, -1.493424654006958, 1.0952887535095215, -1.7703802585601807, -2.4324464797973633, 0.40698888897895813, -5.188541889190674, 3.841076374053955, -3.7766754627227783, -1.2854382991790771, 3.185441017150879, 1.1935969591140747, 0.5826236605644226, -1.2215397357940674, -4.865927219390869, -4.633474349975586, -1.167330026626587, 1.1627209186553955, -0.22295856475830078, -4.211874961853027, 0.2428896427154541, -3.6107473373413086, -3.2735652923583984, 2.875898599624634, 3.7175393104553223, 3.0179100036621094, 4.034282684326172, 1.1873879432678223, 3.092750310897827, -2.482966423034668, 1.3855974674224854, 2.2576937675476074, 0.9120624661445618, -0.7953076362609863, -0.09212826937437057, -0.04562532901763916, -0.2452099323272705, 0.672014594078064, 0.9832779169082642, 0.8954272270202637, -3.2224671840667725, 1.957357406616211, 5.284664630889893, -2.002985954284668, -2.471601724624634, -1.7302770614624023, -2.873502254486084, 1.1295723915100098, -1.5491256713867188, -5.707137584686279, 2.8530421257019043, -0.2643877863883972, 0.8024728298187256, 1.0461363792419434, 0.9237658977508545, -1.3014153242111206, -2.9224014282226562, -1.1175177097320557, -2.6533708572387695, 0.2044965922832489, -2.072725772857666, 0.5080446600914001, 1.5947340726852417, 1.2278187274932861, -1.609885573387146, 0.6639143228530884, 0.2469625025987625, -0.07805928587913513, -2.111103057861328, -3.578428030014038, -1.3685001134872437, 1.9612454175949097, 0.2562447786331177, -0.5922466516494751, 3.855717182159424, -2.6805360317230225, -1.3309810161590576, -0.14805418252944946, 2.4503719806671143, 2.4964418411254883, 2.916283130645752, -2.560709238052368, -1.4271776676177979, -1.4742952585220337, 3.7387516498565674, 1.9097418785095215, 0.1607094407081604, 2.6281399726867676, 1.1268069744110107, -1.959589958190918, -0.7029924392700195, 2.689059257507324, -1.5686848163604736, 0.9398348331451416, -1.9787335395812988, 1.4679707288742065, -4.820215225219727, 2.633965492248535, 1.2595349550247192, -1.4709419012069702, 5.015800476074219, -3.533895969390869, 2.4313130378723145, 1.6752971410751343, 2.812577486038208, -2.6067190170288086, -2.1874210834503174, -4.936158657073975, 6.20560884475708, -1.5726691484451294, 2.5791800022125244, -3.656064987182617, 4.833833694458008, -1.8970681428909302, 4.775002956390381, 2.08392333984375, -0.3414423167705536, -2.7202396392822266, -3.513397693634033, 1.5294971466064453, -0.7259325981140137, 1.961181402206421, 3.8482847213745117, 2.6189215183258057, 3.7842366695404053, 0.08039587736129761, 1.8728827238082886, -2.581357479095459, -1.6711056232452393, 0.8974134922027588, -2.8805346488952637, -2.9208199977874756, 4.3835577964782715, -2.446713924407959, -0.17174774408340454, 5.355374813079834, -1.575836420059204, 0.5388461947441101, 3.286109209060669, 1.7535617351531982, 0.7574344873428345, -2.349799871444702, -3.7714366912841797, 2.6155600547790527, -0.4974636435508728, 2.1626436710357666, 5.7223920822143555, 4.005527973175049, -1.1396621465682983, 7.944160461425781, -2.660799264907837, -1.3134095668792725, -3.9956204891204834, -9.434564590454102, -5.767303466796875, -4.990682601928711, 0.2799413800239563, -3.237804412841797, -2.9255075454711914, -3.1861748695373535, -2.861666202545166, 5.03348970413208, 2.3157730102539062, -3.8089358806610107, -0.24117285013198853, -5.186347007751465, 1.066924810409546, 1.9648782014846802, 1.238943338394165, -0.6590574979782104, 4.292763710021973, -1.5347460508346558, 1.5626903772354126, -0.3241578936576843, 1.9453656673431396, 3.856898307800293, -0.47141915559768677, -2.7094573974609375, 0.47523799538612366, 3.272409677505493, 0.10762891173362732, 2.2162556648254395, 0.8326456546783447, 0.47202202677726746, -7.1059770584106445, 4.218060493469238, 3.896106719970703, -3.5459229946136475, 5.298534393310547, 1.8571503162384033, -0.986137866973877, -5.885499477386475, -3.5143141746520996, -5.025787830352783, -1.6249220371246338, 3.757392168045044, -5.282137393951416, 2.4075257778167725, 1.906000018119812, -2.4602890014648438, -1.1592689752578735, -4.02043342590332, -1.1879253387451172, 1.5408613681793213, 1.454640507698059, 7.608460426330566, -3.239082098007202, 1.7990007400512695, 2.4204137325286865, -1.888704538345337, 3.2249915599823, 3.242872953414917, 4.830099582672119, 2.1452765464782715, 6.881599426269531, 2.2579007148742676, -4.861010551452637, 2.528012990951538, 1.491978645324707, 5.3004841804504395, 1.4966914653778076, 4.28740930557251, -2.170856475830078, 0.06783469766378403, -2.7655692100524902, 0.6727364659309387, -1.0660390853881836, 3.466733455657959, 0.530046284198761, 2.991767644882202, -2.9452333450317383, -1.0527138710021973, -2.8662476539611816, 1.9816136360168457, 1.3402495384216309, -2.19728946685791, -0.00503438338637352, -1.6173782348632812, -1.5154337882995605, -1.398492693901062, 4.60127067565918, -3.6189303398132324, 1.2732025384902954, -5.424232482910156, 4.763565540313721, -0.8359209895133972, 4.297383785247803, 2.88529372215271, -2.295916795730591, 1.1955653429031372, -0.5658209323883057, -4.234613418579102, 5.87252140045166, 2.4539308547973633, 2.1682753562927246, -2.175701856613159, -0.5272976160049438, -1.3904378414154053, -0.6558912992477417, 2.151852607727051, 2.6267266273498535, 6.1862077713012695, -2.236616611480713, -2.46718168258667, 1.6054731607437134, 1.236859917640686, -4.016797065734863, 2.564441442489624, 2.9593474864959717, 1.8453437089920044, 0.8548566102981567, 0.6815851330757141, 1.6342124938964844, 2.0484790802001953, 5.161302089691162, 2.0103867053985596, -2.2268259525299072, -0.324008584022522, -4.525731086730957, -5.899938583374023, -1.57381272315979, 2.753848075866699, 1.4437190294265747, 2.5572738647460938, -4.031088829040527, 1.4342057704925537, -3.0169248580932617, -2.3864011764526367, 3.8081140518188477, 3.15205717086792, -1.2462984323501587, 3.350985050201416, 3.932457447052002, -0.3616705536842346, -1.6752489805221558, -2.0513782501220703, -0.7278816103935242, -3.8056182861328125, -1.077030062675476, 3.3998231887817383, 0.3705006539821625, 3.6883020401000977, -0.20162513852119446, 0.3596533238887787, -3.7134628295898438, -1.9852213859558105, 1.4022072553634644, 1.5042661428451538, -0.9216997623443604, -0.766638994216919, -0.9795191287994385, 3.40193510055542, 5.399808883666992, 1.1797339916229248, 0.17057597637176514, -1.6337227821350098, -2.417093276977539, -1.1497867107391357, -2.319566249847412, 2.289945363998413, 6.71909236907959, -0.9108301401138306, -0.011780805885791779, -1.4741638898849487, 0.1411837786436081, -0.7666654586791992, 1.072249412536621, 2.915128469467163, 5.379716873168945, -2.604185104370117, -1.1876413822174072, 0.5678701400756836, 2.952575206756592, 3.58003830909729, -0.7299574613571167, 3.713240385055542, 2.386962890625, -2.247404098510742, -4.430778503417969, -2.4630932807922363, -1.3351783752441406, 4.594967842102051, 1.2018078565597534, 2.9924888610839844, -0.630717933177948, 2.6290090084075928, -3.2401227951049805, 2.9851884841918945, 0.5099890828132629, -0.32211846113204956, 2.7706260681152344, 0.8954097032546997, -0.04436314105987549, -4.248575210571289, -4.576909065246582, 3.488842487335205, 0.5832319259643555, 2.8054537773132324, -1.4832326173782349, 0.28761956095695496, 2.8485336303710938, -1.296849012374878, -0.6779845356941223, -3.2111666202545166, 1.9787689447402954, -1.5465495586395264, -4.7340474128723145, 0.11345571279525757, -0.14084027707576752, 1.9810600280761719, -1.6290788650512695, -2.043548583984375, -2.949659824371338, 0.9230931401252747, -0.07091890275478363, 0.9788657426834106, -1.612915277481079, -0.19579987227916718, -6.65704345703125, -1.3438419103622437, -3.763821601867676, 1.2558623552322388, 2.140481472015381, -0.6798375844955444, 2.390300750732422, 4.744471549987793, 4.469935417175293, -3.9686341285705566, -1.778070092201233, 3.8076817989349365, 0.5489823222160339, 1.1142582893371582, -3.220423698425293, -0.8057819604873657, -3.0291314125061035, 10.149873733520508, -3.0511834621429443, 1.263113260269165, -4.1305060386657715, -3.896047592163086, -4.279664993286133, -0.8047889471054077, -0.12870952486991882, 2.5159802436828613, 3.704922676086426, -2.0867600440979004, -3.4006495475769043, -1.885886788368225, -3.297698497772217, 1.2235376834869385, -1.4368454217910767, 2.007518768310547, 0.30317431688308716, -3.131901502609253, -1.4268234968185425, 3.5213465690612793, -1.0129806995391846, 0.7158693671226501, -4.522485256195068, -4.235111713409424, 2.054044723510742, 3.979306697845459, 1.3788737058639526, 1.7657277584075928, -1.0772475004196167, 1.0076931715011597, 6.627652645111084, -2.396228790283203, -0.7493685483932495, 0.03169824182987213, 0.7719594240188599, -0.9826122522354126, -2.9704136848449707, -0.14799341559410095, -5.19771671295166, 0.9957502484321594, 2.7101709842681885, -2.450211524963379, 3.224669933319092, -2.9445900917053223, -1.992325782775879, 2.857076406478882, -0.43477949500083923, -6.4996185302734375, 5.825007915496826, -3.0607876777648926, -0.7532831430435181, -5.731386661529541, 2.1117076873779297, 0.7012711763381958, -0.4407273530960083, -2.835089921951294, -2.6022825241088867, -0.48043811321258545, 0.5714886784553528, 1.2276394367218018, 1.9414036273956299, 6.570715427398682, -0.9756608605384827, -2.3062329292297363, 3.374922275543213, -2.6608853340148926, 3.6467506885528564, -1.402575969696045, -1.3301022052764893, -0.47859400510787964, 1.4427119493484497, -0.49938851594924927, -4.236391544342041, 0.777758002281189, -0.9009902477264404, 1.817657232284546, -3.8171029090881348, -1.202553153038025, 3.825739622116089, -3.5488178730010986, -3.9272449016571045, -2.9504148960113525, 0.16043853759765625, 1.6629605293273926, -1.1063730716705322, 1.1721901893615723, 0.8794270157814026, -2.1830575466156006, 1.2237869501113892, -4.064148426055908, -0.9820485711097717, 5.156486988067627, 3.1930830478668213, 2.727524757385254, -4.5054497718811035, -2.9361350536346436, 0.3134649097919464, 0.7734969854354858, -1.2302123308181763, 1.815080165863037, 3.712904453277588, -1.9375901222229004, -0.7238602042198181, -5.060826301574707, 0.13670963048934937, -2.1631834506988525, -2.660275459289551, -3.534555435180664, 0.12559731304645538, 1.3645493984222412, 0.8591627478599548, 3.1643340587615967, 0.5393146872520447, 0.766787052154541, -3.0512771606445312, 1.2689402103424072, -0.3294597864151001, 0.29757222533226013, 3.023794651031494, 3.6919238567352295, 0.6245505809783936, -0.004425600171089172, -4.051902770996094, -0.8448878526687622, 0.03290879726409912, 3.0217368602752686, -2.1936895847320557, -2.591491937637329, -2.7961978912353516, 2.9690139293670654, 1.8845709562301636, 2.0488815307617188, -0.3929055333137512, 3.2013416290283203, -0.02199321985244751, 0.6550448536872864, 0.40371033549308777, 0.9349490404129028, 2.9326210021972656, -0.9087234735488892, 1.6680347919464111, -1.7342610359191895, 5.191349506378174, 0.8320249915122986, 0.632623553276062, -4.146793842315674, -1.180707573890686, 3.647608757019043, 2.951371669769287, 3.1728854179382324, 1.2579790353775024, -2.1136271953582764, -0.9828354716300964, -3.1169707775115967, 2.203051805496216]}, 'authors': [{'authorId': '145585097', 'name': 'Bridger Waleed Ammar'}, {'authorId': '3458736', 'name': 'Dirk Groeneveld'}, {'authorId': '1857797', 'name': 'Chandra Bhagavatula'}, {'authorId': '46181066', 'name': 'Iz Beltagy'}, {'authorId': '46230609', 'name': 'Miles Crawford'}, {'authorId': '145612610', 'name': 'Doug Downey'}, {'authorId': '38092776', 'name': 'Jason Dunkelberger'}, {'authorId': '143718836', 'name': 'Ahmed Elgohary'}, {'authorId': '46411828', 'name': 'Sergey Feldman'}, {'authorId': '4480314', 'name': 'Vu A. Ha'}, {'authorId': '143967880', 'name': 'Rodney Michael Kinney'}, {'authorId': '41018147', 'name': 'Sebastian Kohlmeier'}, {'authorId': '46258841', 'name': 'Kyle Lo'}, {'authorId': '144240185', 'name': 'Tyler C. Murray'}, {'authorId': '46256862', 'name': 'Hsu-Han Ooi'}, {'authorId': '39139825', 'name': 'Matthew E. Peters'}, {'authorId': '39561369', 'name': 'Joanna L. Power'}, {'authorId': '46181683', 'name': 'Sam Skjonsberg'}, {'authorId': '31860505', 'name': 'Lucy Lu Wang'}, {'authorId': '46212260', 'name': 'Christopher Wilhelm'}, {'authorId': '2112339497', 'name': 'Zheng Yuan'}, {'authorId': '15292561', 'name': 'Madeleine van Zuylen'}, {'authorId': '1741101', 'name': 'Oren Etzioni'}], 'references': [{'paperId': '1fec9d41d372267b4474f18cbeadd806c8b67adb', 'title': 'Extracting Scientific Figures with Distantly Supervised Neural Networks'}, {'paperId': '921b2958cac4138d188fd5047aa12bbcf37ac867', 'title': 'Content-Based Citation Recommendation'}, {'paperId': '2264e14e35dc5a3db93437bc408a03171af8c59d', 'title': 'The AI2 system at SemEval-2017 Task 10 (ScienceIE): semi-supervised end-to-end entity and relation extraction'}, {'paperId': '6bed23ebd9998e85bad446b9a56ea53f463d0f8a', 'title': 'Learning to Predict Citation-Based Impact Measures'}, {'paperId': '32ce5467ff884d2f90a233f4d9606c6e18b1a9d6', 'title': 'Learning a Neural Semantic Parser from User Feedback'}, {'paperId': 'a26accf878216be4388ad9a0474e658aa03d33e2', 'title': 'SemEval 2017 Task 10: ScienceIE - Extracting Keyphrases and Relations from Scientific Publications'}, {'paperId': 'b30481dd5467a187b7e1a5a2dd326d97cafd95ac', 'title': 'Explicit Semantic Ranking for Academic Search via Knowledge Graph Embedding'}, {'paperId': '0bb4cadc80c0afaf29c57518dc9c06f8fcfa5f38', 'title': 'Semi-supervised sequence tagging with bidirectional language models'}, {'paperId': '74a69228157b3fa1c7adc14e7715039e54f4b067', 'title': 'MetaMap Lite: an evaluation of a new Java implementation of MetaMap'}, {'paperId': '61322ec6cfc54fe9723d4637239b8fb9938dc501', 'title': 'BioCreative V CDR task corpus: a resource for chemical disease relation extraction'}, {'paperId': 'f5a7da72496e2ca8edcd9f9123773012c010cfc6', 'title': 'Neural Architectures for Named Entity Recognition'}, {'paperId': '8ffcad9346c4978a211566fde6807d6fb4bfa5ed', 'title': 'TabEL: Entity Linking in Web Tables'}, {'paperId': 'c6b53dd64d79a59f49f261baac8d2581a29ca06a', 'title': 'Design Challenges for Entity Linking'}, {'paperId': '1c7be3fc28296a97607d426f9168ad4836407e4b', 'title': 'Identifying Meaningful Citations'}, {'paperId': 'd755a7e943009af26e0a5b617ef60c29c1d4f4e0', 'title': 'CHEMDNER: The drugs and chemical names extraction challenge'}, {'paperId': 'f37e1b62a767a307c046404ca96bc140b3e68cb5', 'title': 'GloVe: Global Vectors for Word Representation'}, {'paperId': 'dfb25cf7efec9a7c114f6327e4b06a306cce5cb6', 'title': 'CiteSeerX: AI in a Digital Library Search Engine'}, {'paperId': '43bfbc53482a83e2141d044493ccbb65a472be55', 'title': 'Clinical review: Efficacy of antimicrobial-impregnated catheters in external ventricular drainage - a systematic review and meta-analysis'}, {'paperId': 'e23020fdab3e46254468f694c159d7d6a3a9fb55', 'title': 'Search needs a shake-up'}, {'paperId': 'ecfaab27ac62f6a63146b6d75ae9f9d232abd31b', 'title': 'Exploiting MeSH indexing in MEDLINE to generate a data set for word sense disambiguation'}, {'paperId': 'bc1022b031dc

In [7]:
crossref_data = pd.read_csv("./papers_data_from_rcrossref_Arabic world_cleaned.csv")
crossref_data.head()

C:\Users\Sohaila\AppData\Local\Temp\ipykernel_4208\399524737.py:1: DtypeWarning: Columns (4,20,22,23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  crossref_data = pd.read_csv("./papers_data_from_rcrossref_Arabic world_cleaned.csv")

,Unnamed: 0.1,container.title,created,deposited,published.print,doi,indexed,issued,member,prefix,...,type,url,author,link,reference,issn,issue,volume,page,language
0,0.0,Race,2008-03-29,2021-01-24,1965-04,10.1177/030639686500600401,2022-04-03,1965-04,179,10.1177,...,journal-article,http://dx.doi.org/10.1177/030639686500600401,"[{""given"":""Patrick"",""family"":""Duncan"",""sequenc...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""atypb1"",""volume.title"":""House of Asse...",NaN,NaN,NaN,NaN,NaN
1,2.0,The Journal of Chemical Physics,2004-02-04,2024-02-09,1969-01-15,10.1063/1.1671082,2024-02-09,1969-01-15,317,10.1063,...,journal-article,http://dx.doi.org/10.1063/1.1671082,"[{""given"":""J."",""family"":""Fourny"",""sequence"":""f...","c(""https://pubs.aip.org/aip/jcp/article-pdf/50...","[{""key"":""2024020904355486600_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
2,3.0,Journal of Mathematical Physics,2004-02-10,2024-02-07,1970-07-01,10.1063/1.1665375,2024-07-02,1970-07-01,317,10.1063,...,journal-article,http://dx.doi.org/10.1063/1.1665375,"[{""given"":""B."",""family"":""Picinbono"",""sequence""...","c(""https://pubs.aip.org/aip/jmp/article-pdf/11...","[{""key"":""2024020706263321400_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
3,5.0,Journal of Palestine Studies,2012-09-12,2021-02-13,1971-10-01,10.2307/2535999,2022-04-03,1971-10-01,301,10.1080,...,journal-article,http://dx.doi.org/10.2307/2535999,"[{""given"":""William B."",""family"":""Quandt"",""sequ...","c(""http://online.ucpress.edu/jps/article-pdf/1...","[{""key"":""CIT0001"",""unstructured"":""New York Tim...",NaN,NaN,NaN,NaN,NaN
4,7.0,Annals of Clinical Biochemistry: International...,2014-02-05,2022-03-25,1978-01,10.1177/000456327801500135,2022-03-31,1978-01,179,10.1177,...,journal-article,http://dx.doi.org/10.1177/000456327801500135,"[{""given"":""D."",""family"":""Allard"",""sequence"":""f...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""bibr1-000456327801500135"",""first.page...",NaN,NaN,NaN,NaN,NaN

In [8]:
crossref_data.columns

Index(['Unnamed: 0.1', 'container.title', 'created', 'deposited',
       'published.print', 'doi', 'indexed', 'issued', 'member', 'prefix',
       'publisher', 'score', 'source', 'reference.count', 'references.count',
       'is.referenced.by.count', 'title', 'type', 'url', 'author', 'link',
       'reference', 'issn', 'issue', 'volume', 'page', 'language'],
      dtype='object')

In [9]:
crossref_data = crossref_data.drop(columns = ["Unnamed: 0.1"])

In [10]:
crossref_data.head()

,container.title,created,deposited,published.print,doi,indexed,issued,member,prefix,publisher,...,type,url,author,link,reference,issn,issue,volume,page,language
0,Race,2008-03-29,2021-01-24,1965-04,10.1177/030639686500600401,2022-04-03,1965-04,179,10.1177,SAGE Publications,...,journal-article,http://dx.doi.org/10.1177/030639686500600401,"[{""given"":""Patrick"",""family"":""Duncan"",""sequenc...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""atypb1"",""volume.title"":""House of Asse...",NaN,NaN,NaN,NaN,NaN
1,The Journal of Chemical Physics,2004-02-04,2024-02-09,1969-01-15,10.1063/1.1671082,2024-02-09,1969-01-15,317,10.1063,AIP Publishing,...,journal-article,http://dx.doi.org/10.1063/1.1671082,"[{""given"":""J."",""family"":""Fourny"",""sequence"":""f...","c(""https://pubs.aip.org/aip/jcp/article-pdf/50...","[{""key"":""2024020904355486600_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
2,Journal of Mathematical Physics,2004-02-10,2024-02-07,1970-07-01,10.1063/1.1665375,2024-07-02,1970-07-01,317,10.1063,AIP Publishing,...,journal-article,http://dx.doi.org/10.1063/1.1665375,"[{""given"":""B."",""family"":""Picinbono"",""sequence""...","c(""https://pubs.aip.org/aip/jmp/article-pdf/11...","[{""key"":""2024020706263321400_r1""},{""key"":""2024...",NaN,NaN,NaN,NaN,NaN
3,Journal of Palestine Studies,2012-09-12,2021-02-13,1971-10-01,10.2307/2535999,2022-04-03,1971-10-01,301,10.1080,Informa UK Limited,...,journal-article,http://dx.doi.org/10.2307/2535999,"[{""given"":""William B."",""family"":""Quandt"",""sequ...","c(""http://online.ucpress.edu/jps/article-pdf/1...","[{""key"":""CIT0001"",""unstructured"":""New York Tim...",NaN,NaN,NaN,NaN,NaN
4,Annals of Clinical Biochemistry: International...,2014-02-05,2022-03-25,1978-01,10.1177/000456327801500135,2022-03-31,1978-01,179,10.1177,SAGE Publications,...,journal-article,http://dx.doi.org/10.1177/000456327801500135,"[{""given"":""D."",""family"":""Allard"",""sequence"":""f...","c(""http://journals.sagepub.com/doi/pdf/10.1177...","[{""key"":""bibr1-000456327801500135"",""first.page...",NaN,NaN,NaN,NaN,NaN

In [11]:
size_crossref_data = len(crossref_data)
print(size_crossref_data)

333260

In [34]:
def get_references (paper_doi):
    # Define the API endpoint URL
    url = f"http://api.semanticscholar.org/graph/v1/paper/{paper_doi}"

    # Define the query parameters
    query_params = {"fields": "title,authors,references,year"}

    # Directly define the API key (Reminder: Securely handle API keys in production environments)
    api_key = "your api key goes here"  # Replace with the actual API key

    # Send the API request
    response = requests.get(url, params=query_params)

    # Check response status
    if response.status_code == 200:
        response_data = response.json()
        print("prossised a paper")
        # Process and print the response data as needed
        return(response_data["references"])
    else:
        print("prossesing failed")
        return None

In [36]:
crossref_data["references"] = crossref_data["doi"].apply(get_references)

prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossesing failed
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper
prossised a paper

KeyboardInterrupt:

In [12]:
papers_dois = crossref_data["doi"]
print(papers_dois)

0            10.1177/030639686500600401
1                     10.1063/1.1671082
2                     10.1063/1.1665375
3                       10.2307/2535999
4            10.1177/000456327801500135
                      ...
333255    10.1080/20008066.2024.2358681
333256           10.1093/mnras/stae1509
333257               10.1002/jpn3.12188
333258               10.1002/ece3.11561
333259            10.1099/mgen.0.001260
Name: doi, Length: 333260, dtype: object

In [13]:
papers_dois = papers_dois.to_list()
print(papers_dois[0:10])

['10.1177/030639686500600401', '10.1063/1.1671082', '10.1063/1.1665375', '10.2307/2535999', '10.1177/000456327801500135', '10.1063/1.863593', '10.1785/bssa07206a2227', '10.2514/6.1983-137', '10.1061/(asce)0733-9445(1983)109:8(1903)', '10.1002/1097-0142(19841101)54:9<1908::aid-cncr2820540922>3.0.co;2-#']

In [14]:
output_csv_path = './papers_data_from_symantic_scholar_Arabic world_2.csv'

In [22]:
with open(output_csv_path, mode='w', newline='', encoding='utf-8') as output_file:
    fieldnames = ['Paper Id' , 'title', 'authors', 'citationCount', 'references', 'year', 'isOpenAccess', 'externalIds', 'publicationDate', 'embedding']
    writer = csv.DictWriter(output_file, fieldnames=fieldnames)
    writer.writeheader()

    for i in range (0,len(papers_dois),500):  
        url = 'https://api.semanticscholar.org/graph/v1/paper/batch'
        query_params = {"fields": "title,authors,citationCount,references,url,fieldsOfStudy,year,isOpenAccess,externalIds,paperId,publicationDate,embedding"}
        api_key = "9zJhKmoKKZ5OyKBkPj6rK6zWa1oxTizegHHhNT6g"
        headers = {"x-api-key": api_key}
        papers_details = requests.post(
            url,
            params= query_params,
            json={"ids": papers_dois[i:i+500]},
            headers=headers
        )

        try:
            papers_details = papers_details.json()
        except ValueError as e:
            print(f"Error parsing JSON at batch {i}: {e}")
            continue

        if not isinstance(papers_details, list):
            print(f"Unexpected response format at batch {i}: {papers_details}")
            continue

        for paper in papers_details:
            if paper:
                data_to_save = {
                    'Paper Id': paper["paperId"],
                    'title': paper["title"],
                    'authors': paper["authors"],
                    'citationCount': paper["citationCount"],
                    'references': paper["references"],
                    'year': paper["year"],
                    'isOpenAccess': paper["isOpenAccess"],
                    'externalIds': paper["externalIds"],
                    'publicationDate': paper["publicationDate"],
                    'embedding': paper["embedding"]
                }
                writer.writerow(data_to_save)

        print(f"prossesed {i + 500} papers")

prossesed 500 papers
prossesed 1000 papers
prossesed 1500 papers
prossesed 2000 papers
prossesed 2500 papers
prossesed 3000 papers
prossesed 3500 papers
prossesed 4000 papers
prossesed 4500 papers
prossesed 5000 papers
prossesed 5500 papers
prossesed 6000 papers
prossesed 6500 papers
prossesed 7000 papers
prossesed 7500 papers
prossesed 8000 papers
prossesed 8500 papers
prossesed 9000 papers
prossesed 9500 papers
prossesed 10000 papers
prossesed 10500 papers
prossesed 11000 papers
prossesed 11500 papers
prossesed 12000 papers
prossesed 12500 papers
prossesed 13000 papers
prossesed 13500 papers
prossesed 14000 papers
prossesed 14500 papers
prossesed 15000 papers
prossesed 15500 papers
prossesed 16000 papers
prossesed 16500 papers
prossesed 17000 papers
prossesed 17500 papers
prossesed 18000 papers
prossesed 18500 papers
prossesed 19000 papers
prossesed 19500 papers
prossesed 20000 papers
prossesed 20500 papers
prossesed 21000 papers
prossesed 21500 papers
prossesed 22000 papers
prossesed 22500 papers
prossesed 23000 papers
prossesed 23500 papers
prossesed 24000 papers
prossesed 24500 papers
prossesed 25000 papers
prossesed 25500 papers
prossesed 26000 papers
prossesed 26500 papers
prossesed 27000 papers
prossesed 27500 papers
prossesed 28000 papers
prossesed 28500 papers
prossesed 29000 papers
prossesed 29500 papers
prossesed 30000 papers
prossesed 30500 papers
prossesed 31000 papers
prossesed 31500 papers
prossesed 32000 papers
prossesed 32500 papers
prossesed 33000 papers
prossesed 33500 papers
prossesed 34000 papers
prossesed 34500 papers
prossesed 35000 papers
prossesed 35500 papers
prossesed 36000 papers
prossesed 36500 papers
prossesed 37000 papers
prossesed 37500 papers
prossesed 38000 papers
prossesed 38500 papers
prossesed 39000 papers
prossesed 39500 papers
prossesed 40000 papers
prossesed 40500 papers
prossesed 41000 papers
prossesed 41500 papers
prossesed 42000 papers
prossesed 42500 papers
prossesed 43000 papers
prossesed 43500 papers
prossesed 44000 papers
prossesed 44500 papers
prossesed 45000 papers
prossesed 45500 papers
prossesed 46000 papers
prossesed 46500 papers
prossesed 47000 papers
prossesed 47500 papers
prossesed 48000 papers
prossesed 48500 papers
prossesed 49000 papers
prossesed 49500 papers
prossesed 50000 papers
prossesed 50500 papers
prossesed 51000 papers
prossesed 51500 papers
prossesed 52000 papers
prossesed 52500 papers
prossesed 53000 papers
prossesed 53500 papers
prossesed 54000 papers
prossesed 54500 papers
prossesed 55000 papers
prossesed 55500 papers
prossesed 56000 papers
prossesed 56500 papers
prossesed 57000 papers
prossesed 57500 papers
prossesed 58000 papers
prossesed 58500 papers
prossesed 59000 papers
prossesed 59500 papers
prossesed 60000 papers
prossesed 60500 papers
prossesed 61000 papers
prossesed 61500 papers
prossesed 62000 papers
prossesed 62500 papers
prossesed 63000 papers
prossesed 63500 papers
prossesed 64000 papers
prossesed 64500 papers
prossesed 65000 papers
prossesed 65500 papers
prossesed 66000 papers
prossesed 66500 papers
prossesed 67000 papers
prossesed 67500 papers
prossesed 68000 papers
prossesed 68500 papers
prossesed 69000 papers
prossesed 69500 papers
prossesed 70000 papers
prossesed 70500 papers
prossesed 71000 papers
prossesed 71500 papers
prossesed 72000 papers
prossesed 72500 papers
prossesed 73000 papers
prossesed 73500 papers
prossesed 74000 papers
prossesed 74500 papers
prossesed 75000 papers
prossesed 75500 papers
prossesed 76000 papers
prossesed 76500 papers
prossesed 77000 papers
prossesed 77500 papers
prossesed 78000 papers
prossesed 78500 papers
prossesed 79000 papers
prossesed 79500 papers
prossesed 80000 papers
prossesed 80500 papers
prossesed 81000 papers
prossesed 81500 papers
prossesed 82000 papers
prossesed 82500 papers
prossesed 83000 papers
prossesed 83500 papers
prossesed 84000 papers
prossesed 84500 papers
prossesed 85000 papers
prossesed 85500 papers
prossesed 86000 papers
prossesed 86500 papers
Unexpected response format at batch 86500: {'message': 'Network error communicating with endpoint'}
prossesed 87500 papers
prossesed 88000 papers
prossesed 88500 papers
prossesed 89000 papers
prossesed 89500 papers
prossesed 90000 papers
prossesed 90500 papers
prossesed 91000 papers
prossesed 91500 papers
prossesed 92000 papers
prossesed 92500 papers
prossesed 93000 papers
prossesed 93500 papers
prossesed 94000 papers
prossesed 94500 papers
prossesed 95000 papers
prossesed 95500 papers
prossesed 96000 papers
prossesed 96500 papers
prossesed 97000 papers
prossesed 97500 papers
prossesed 98000 papers
prossesed 98500 papers
prossesed 99000 papers
prossesed 99500 papers
prossesed 100000 papers
prossesed 100500 papers
prossesed 101000 papers
prossesed 101500 papers
prossesed 102000 papers
prossesed 102500 papers
prossesed 103000 papers
prossesed 103500 papers
prossesed 104000 papers
prossesed 104500 papers
prossesed 105000 papers
prossesed 105500 papers
prossesed 106000 papers
prossesed 106500 papers
prossesed 107000 papers
prossesed 107500 papers
prossesed 108000 papers
prossesed 108500 papers
prossesed 109000 papers
prossesed 109500 papers
prossesed 110000 papers
prossesed 110500 papers
prossesed 111000 papers
prossesed 111500 papers
prossesed 112000 papers
prossesed 112500 papers
prossesed 113000 papers
prossesed 113500 papers
prossesed 114000 papers
prossesed 114500 papers
prossesed 115000 papers
prossesed 115500 papers
prossesed 116000 papers
prossesed 116500 papers
prossesed 117000 papers
prossesed 117500 papers
prossesed 118000 papers
prossesed 118500 papers
prossesed 119000 papers
prossesed 119500 papers
prossesed 120000 papers
prossesed 120500 papers
prossesed 121000 papers
prossesed 121500 papers
prossesed 122000 papers
prossesed 122500 papers
prossesed 123000 papers
prossesed 123500 papers
prossesed 124000 papers
prossesed 124500 papers
prossesed 125000 papers
prossesed 125500 papers
prossesed 126000 papers
prossesed 126500 papers
prossesed 127000 papers
prossesed 127500 papers
prossesed 128000 papers
prossesed 128500 papers
prossesed 129000 papers
prossesed 129500 papers
prossesed 130000 papers
prossesed 130500 papers
prossesed 131000 papers
prossesed 131500 papers
prossesed 132000 papers
prossesed 132500 papers
prossesed 133000 papers
prossesed 133500 papers
prossesed 134000 papers
prossesed 134500 papers
prossesed 135000 papers
prossesed 135500 papers
prossesed 136000 papers
prossesed 136500 papers
prossesed 137000 papers
prossesed 137500 papers
prossesed 138000 papers
prossesed 138500 papers
prossesed 139000 papers
prossesed 139500 papers
prossesed 140000 papers
prossesed 140500 papers
prossesed 141000 papers
prossesed 141500 papers
prossesed 142000 papers
prossesed 142500 papers
prossesed 143000 papers
prossesed 143500 papers
prossesed 144000 papers
prossesed 144500 papers
prossesed 145000 papers
prossesed 145500 papers
prossesed 146000 papers
prossesed 146500 papers
prossesed 147000 papers
prossesed 147500 papers
prossesed 148000 papers
prossesed 148500 papers
prossesed 149000 papers
prossesed 149500 papers
prossesed 150000 papers
prossesed 150500 papers
prossesed 151000 papers
prossesed 151500 papers
prossesed 152000 papers
prossesed 152500 papers
prossesed 153000 papers
prossesed 153500 papers
prossesed 154000 papers
prossesed 154500 papers
prossesed 155000 papers
prossesed 155500 papers
prossesed 156000 papers
prossesed 156500 papers
prossesed 157000 papers
prossesed 157500 papers
prossesed 158000 papers
prossesed 158500 papers
prossesed 159000 papers
prossesed 159500 papers
prossesed 160000 papers
prossesed 160500 papers
prossesed 161000 papers
prossesed 161500 papers
prossesed 162000 papers
prossesed 162500 papers
prossesed 163000 papers
prossesed 163500 papers
prossesed 164000 papers
prossesed 164500 papers
prossesed 165000 papers
prossesed 165500 papers
prossesed 166000 papers
prossesed 166500 papers
prossesed 167000 papers
prossesed 167500 papers
prossesed 168000 papers
prossesed 168500 papers
prossesed 169000 papers
prossesed 169500 papers
prossesed 170000 papers
prossesed 170500 papers
prossesed 171000 papers
prossesed 171500 papers
prossesed 172000 papers
prossesed 172500 papers
prossesed 173000 papers
prossesed 173500 papers
prossesed 174000 papers
prossesed 174500 papers
prossesed 175000 papers
prossesed 175500 papers
prossesed 176000 papers
prossesed 176500 papers
prossesed 177000 papers
prossesed 177500 papers
prossesed 178000 papers
prossesed 178500 papers
prossesed 179000 papers
prossesed 179500 papers
prossesed 180000 papers
prossesed 180500 papers
prossesed 181000 papers
prossesed 181500 papers
prossesed 182000 papers
prossesed 182500 papers
prossesed 183000 papers
prossesed 183500 papers
prossesed 184000 papers
prossesed 184500 papers
prossesed 185000 papers
prossesed 185500 papers
prossesed 186000 papers
prossesed 186500 papers
prossesed 187000 papers
prossesed 187500 papers
prossesed 188000 papers
prossesed 188500 papers
prossesed 189000 papers
prossesed 189500 papers
prossesed 190000 papers
prossesed 190500 papers
prossesed 191000 papers
prossesed 191500 papers
prossesed 192000 papers
prossesed 192500 papers
prossesed 193000 papers
prossesed 193500 papers
prossesed 194000 papers
prossesed 194500 papers
prossesed 195000 papers
prossesed 195500 papers
prossesed 196000 papers
prossesed 196500 papers
prossesed 197000 papers
prossesed 197500 papers
prossesed 198000 papers
prossesed 198500 papers
prossesed 199000 papers
prossesed 199500 papers
prossesed 200000 papers
prossesed 200500 papers
prossesed 201000 papers
prossesed 201500 papers
prossesed 202000 papers
prossesed 202500 papers
prossesed 203000 papers
prossesed 203500 papers
prossesed 204000 papers
prossesed 204500 papers
prossesed 205000 papers
prossesed 205500 papers
prossesed 206000 papers
prossesed 206500 papers
prossesed 207000 papers
prossesed 207500 papers
prossesed 208000 papers
prossesed 208500 papers
prossesed 209000 papers
prossesed 209500 papers
prossesed 210000 papers
prossesed 210500 papers
prossesed 211000 papers
prossesed 211500 papers
prossesed 212000 papers
prossesed 212500 papers
prossesed 213000 papers
prossesed 213500 papers
prossesed 214000 papers
prossesed 214500 papers
prossesed 215000 papers
prossesed 215500 papers
prossesed 216000 papers
prossesed 216500 papers
prossesed 217000 papers
prossesed 217500 papers
prossesed 218000 papers
prossesed 218500 papers
prossesed 219000 papers
prossesed 219500 papers
prossesed 220000 papers
prossesed 220500 papers
prossesed 221000 papers
prossesed 221500 papers
prossesed 222000 papers
prossesed 222500 papers
prossesed 223000 papers
prossesed 223500 papers
prossesed 224000 papers
prossesed 224500 papers
prossesed 225000 papers
prossesed 225500 papers
prossesed 226000 papers
prossesed 226500 papers
prossesed 227000 papers
prossesed 227500 papers
prossesed 228000 papers
prossesed 228500 papers
prossesed 229000 papers
prossesed 229500 papers
prossesed 230000 papers
prossesed 230500 papers
prossesed 231000 papers
prossesed 231500 papers
prossesed 232000 papers
prossesed 232500 papers
prossesed 233000 papers
prossesed 233500 papers
prossesed 234000 papers
prossesed 234500 papers
prossesed 235000 papers
prossesed 235500 papers
prossesed 236000 papers
prossesed 236500 papers
prossesed 237000 papers
prossesed 237500 papers
prossesed 238000 papers
prossesed 238500 papers
prossesed 239000 papers
prossesed 239500 papers
prossesed 240000 papers
prossesed 240500 papers
prossesed 241000 papers
prossesed 241500 papers
prossesed 242000 papers
prossesed 242500 papers
prossesed 243000 papers
prossesed 243500 papers
prossesed 244000 papers
prossesed 244500 papers
prossesed 245000 papers
prossesed 245500 papers
prossesed 246000 papers
prossesed 246500 papers
prossesed 247000 papers
prossesed 247500 papers
prossesed 248000 papers
prossesed 248500 papers
prossesed 249000 papers
prossesed 249500 papers
prossesed 250000 papers
prossesed 250500 papers
prossesed 251000 papers
prossesed 251500 papers
prossesed 252000 papers
prossesed 252500 papers
prossesed 253000 papers
prossesed 253500 papers
prossesed 254000 papers
prossesed 254500 papers
prossesed 255000 papers
prossesed 255500 papers
prossesed 256000 papers
prossesed 256500 papers
prossesed 257000 papers
prossesed 257500 papers
prossesed 258000 papers
prossesed 258500 papers
prossesed 259000 papers
prossesed 259500 papers
prossesed 260000 papers
prossesed 260500 papers
prossesed 261000 papers
prossesed 261500 papers
prossesed 262000 papers
prossesed 262500 papers
prossesed 263000 papers
prossesed 263500 papers
prossesed 264000 papers
prossesed 264500 papers
prossesed 265000 papers
prossesed 265500 papers
prossesed 266000 papers
prossesed 266500 papers
prossesed 267000 papers
prossesed 267500 papers
prossesed 268000 papers
prossesed 268500 papers
prossesed 269000 papers
prossesed 269500 papers
prossesed 270000 papers
prossesed 270500 papers
prossesed 271000 papers
prossesed 271500 papers
prossesed 272000 papers
prossesed 272500 papers
prossesed 273000 papers
prossesed 273500 papers
prossesed 274000 papers
prossesed 274500 papers
prossesed 275000 papers
prossesed 275500 papers
prossesed 276000 papers
prossesed 276500 papers
prossesed 277000 papers
prossesed 277500 papers
prossesed 278000 papers
prossesed 278500 papers
prossesed 279000 papers
prossesed 279500 papers
prossesed 280000 papers
prossesed 280500 papers
prossesed 281000 papers
prossesed 281500 papers
prossesed 282000 papers
prossesed 282500 papers
prossesed 283000 papers
prossesed 283500 papers
prossesed 284000 papers
prossesed 284500 papers
prossesed 285000 papers
prossesed 285500 papers
prossesed 286000 papers
prossesed 286500 papers
prossesed 287000 papers
Unexpected response format at batch 287000: {'message': 'Endpoint request timed out'}
prossesed 288000 papers
prossesed 288500 papers
prossesed 289000 papers
prossesed 289500 papers
prossesed 290000 papers
prossesed 290500 papers
prossesed 291000 papers
prossesed 291500 papers
prossesed 292000 papers
prossesed 292500 papers
prossesed 293000 papers
prossesed 293500 papers
prossesed 294000 papers
prossesed 294500 papers
prossesed 295000 papers
prossesed 295500 papers
prossesed 296000 papers
prossesed 296500 papers
prossesed 297000 papers
prossesed 297500 papers
prossesed 298000 papers
prossesed 298500 papers
prossesed 299000 papers
prossesed 299500 papers
prossesed 300000 papers
prossesed 300500 papers
prossesed 301000 papers
prossesed 301500 papers
prossesed 302000 papers
prossesed 302500 papers
prossesed 303000 papers
prossesed 303500 papers
prossesed 304000 papers
prossesed 304500 papers
prossesed 305000 papers
prossesed 305500 papers
prossesed 306000 papers
prossesed 306500 papers
prossesed 307000 papers
prossesed 307500 papers
prossesed 308000 papers
prossesed 308500 papers
prossesed 309000 papers
prossesed 309500 papers
prossesed 310000 papers
prossesed 310500 papers
prossesed 311000 papers
prossesed 311500 papers
prossesed 312000 papers
prossesed 312500 papers
prossesed 313000 papers
prossesed 313500 papers
prossesed 314000 papers
prossesed 314500 papers
prossesed 315000 papers
prossesed 315500 papers
prossesed 316000 papers
prossesed 316500 papers
prossesed 317000 papers
prossesed 317500 papers
prossesed 318000 papers
prossesed 318500 papers
prossesed 319000 papers
prossesed 319500 papers
prossesed 320000 papers
prossesed 320500 papers
prossesed 321000 papers
prossesed 321500 papers
prossesed 322000 papers
prossesed 322500 papers
prossesed 323000 papers
prossesed 323500 papers
prossesed 324000 papers
prossesed 324500 papers
prossesed 325000 papers
prossesed 325500 papers
prossesed 326000 papers
prossesed 326500 papers
prossesed 327000 papers

OSError: [Errno 28] No space left on device

In [23]:
sym_data = pd.read_csv("./papers_data_from_symantic_scholar_Arabic world_2.csv")
sym_data.head()

,Paper Id,title,authors,citationCount,references,year,isOpenAccess,externalIds,publicationDate,embedding
0,535792245cc12fb247589d432cbdf5a7e2cd269c,Is apartheid an Insoluble Problem ?,"[{'authorId': '115650133', 'name': 'P. Duncan'}]",1,"[{'paperId': None, 'title': 'House of Assembly...",1965.0,False,"{'MAG': '2159240322', 'DOI': '10.1177/03063968...",1965-04-01,NaN
1,75e6daf6daea4141a1be410ef8e4de2b5a124e71,High‐Temperature Dependence of Electron and Ho...,"[{'authorId': '12146551', 'name': 'J. Fourny'}...",19,[{'paperId': '96f964d99a329c7e9ec26d4a59b9d36b...,1969.0,False,"{'MAG': '2009836093', 'DOI': '10.1063/1.167108...",1969-01-15,NaN
2,f4aaa14a867a7309eb6cba0d3c0bd02ddb3dff56,Photoelectron Shot Noise,"[{'authorId': '1722664', 'name': 'B. Picinbono...",35,[{'paperId': '65531177d3e9e7c4ad45c11a339bd3df...,1970.0,True,"{'MAG': '2083382325', 'DOI': '10.1063/1.166537...",1970-07-01,NaN
3,2a42d3429bab0a9c85732494ce3a7c1beea72470,"The Middle East Conflict in US Strategy, 1970-71","[{'authorId': '98381763', 'name': 'W. Quandt'}]",4,[],1971.0,False,"{'MAG': '2136915275', 'DOI': '10.2307/2535999'...",1971-10-01,NaN
4,5e70f790e6d7a27b9666b84c406337d9128312af,Assay of Tissue Free Cystine: Application to t...,"[{'authorId': '49614845', 'name': 'D. Allard'}...",1,[{'paperId': '282c108edfc7831725598f40aa5f387a...,1978.0,True,"{'MAG': '2083791394', 'DOI': '10.1177/00045632...",1978-01-01,NaN

In [25]:
size_sym_data = len(sym_data)
print(size_sym_data)

318177

In [28]:
print(sym_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318177 entries, 0 to 318176
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Paper Id         318177 non-null  object
 1   title            318177 non-null  object
 2   authors          318177 non-null  object
 3   citationCount    318177 non-null  int64
 4   references       318177 non-null  object
 5   year             318131 non-null  float64
 6   isOpenAccess     318177 non-null  bool
 7   externalIds      318177 non-null  object
 8   publicationDate  300960 non-null  object
 9   embedding        229978 non-null  object
dtypes: bool(1), float64(1), int64(1), object(7)
memory usage: 22.2+ MB
None

In [29]:
print(sym_data.columns)

Index(['Paper Id', 'title', 'authors', 'citationCount', 'references', 'year',
       'isOpenAccess', 'externalIds', 'publicationDate', 'embedding'],
      dtype='object')

In [30]:
num_unique_doi = len(sym_data["Paper Id"].unique())
print(num_unique_doi)

318177